spring:
  logging:
    level:
      web: DEBUG
      root: INFO
  datasource:
    username: user
    url: jdbc:h2:mem:project5DB;DB_CLOSE_ON_EXIT=FALSE
    password: password
  h2:
    console:
      enabled: 'true'
      path:
        settings:
          web-allow-others: 'true'
        nodeValue: /h2console/
  jpa:
    show-sql: 'true'